development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: otrs_development
  pool: 5
  username: root
  password: root
  # JRuby doesn't support # JRuby doesn't support # JRuby doesn't support socket:
                                                  #socket:
                          ## JRuby doesn't support socket:
                           #socket:
  host: 127.0.0.1
  ## JRuby doesn't support # JRuby doesn't support socket:
